apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
      {{- include "helm-chart.labels" . | nindent 8 }}
    name: '{{ include "helm-chart.fullname" . }}'
    namespace: '{{.Release.Namespace}}'
spec:
    replicas: 1
    selector:
        matchLabels:
            {{- include "helm-chart.selectorLabels" . | nindent 10 }}
    template:
        metadata:
            annotations:
                {{- range keys .Values.podAnnotations }}
                {{ . | quote }}: {{ get $.Values.podAnnotations . | quote}}
                {{- end }}
            labels:
                {{- include "helm-chart.selectorLabels" . | nindent 14}}
        spec:
            {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
            {{- toYaml . | nindent 6 }}
            {{- end }}
            containers:
              - args:
                  - --secure-listen-address=0.0.0.0:8443
                  - --upstream=http://127.0.0.1:8080/
                  - --logtostderr=true
                  - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                  - containerPort: 8443
                    name: https
                    protocol: TCP
                resources:
                    limits:
                        cpu: 500m
                        memory: 128Mi
                    requests:
                        cpu: 5m
                        memory: 64Mi
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                          - ALL
              - args:
                  - --health-probe-bind-address=:8081
                  - --metrics-bind-address=127.0.0.1:8080
                  - --challenger-bind-address=127.0.0.1:8082
                  - --leader-elect
                  - --namespace={{.Release.Namespace}}
                command:
                  - /manager
                image: '{{ .Values.image.repository | default "quay.io/kairos/kcrypt-challenger" }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
                livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8081
                    initialDelaySeconds: 15
                    periodSeconds: 20
                name: manager
                readinessProbe:
                    httpGet:
                        path: /readyz
                        port: 8081
                    initialDelaySeconds: 5
                    periodSeconds: 10
                resources:
                    limits:
                        cpu: 500m
                        memory: 128Mi
                    requests:
                        cpu: 10m
                        memory: 64Mi
                {{- if and .Values.resources .Values.resources.controller }}
                resources:
{{ toYaml .Values.resources.controller | indent 20 }}
                {{- end }}
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                          - ALL
            securityContext:
                runAsNonRoot: true
            serviceAccountName: '{{ include "helm-chart.serviceAccountName" . }}'
            terminationGracePeriodSeconds: 10
            {{- with .Values.nodeSelector }}
            nodeSelector:
            {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.affinity }}
            affinity:
            {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.tolerations }}
            tolerations:
            {{- toYaml . | nindent 8 }}
            {{- end }}