apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: kcrypt-controller-leader-election-role
    namespace: '{{.Release.Namespace}}'
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: kcrypt-controller-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - keyserver.kairos.io
    resources:
      - sealedvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keyserver.kairos.io
    resources:
      - sealedvolumes/finalizers
    verbs:
      - update
  - apiGroups:
      - keyserver.kairos.io
    resources:
      - sealedvolumes/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: kcrypt-controller-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: kcrypt-controller-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: kcrypt-controller-leader-election-rolebinding
    namespace: '{{.Release.Namespace}}'
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kcrypt-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: '{{ include "helm-chart.serviceAccountName" . }}'
    namespace: '{{.Release.Namespace}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: kcrypt-controller-manager-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kcrypt-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: '{{ include "helm-chart.serviceAccountName" . }}'
    namespace: '{{.Release.Namespace}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: kcrypt-controller-proxy-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: kcrypt-controller-proxy-role
subjects:
  - kind: ServiceAccount
    name: '{{ include "helm-chart.serviceAccountName" . }}'
    namespace: '{{.Release.Namespace}}'
