apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: '{{ include "helm-chart.fullname" . }}-metrics-service'
  namespace: '{{.Release.Namespace}}'
spec:
 ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
 selector:
    {{- include "helm-chart.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "helm-chart.fullname" . }}-escrow-service'
  namespace: '{{.Release.Namespace}}'
  labels:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.challenger.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.challenger.type | default "ClusterIP" }}
  {{- if eq .Values.service.challenger.type "LoadBalancer" }}
  {{- if .Values.service.challenger.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.challenger.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.service.challenger.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.challenger.loadBalancerSourceRanges }}
    - {{ . }}
  {{- end }}
  {{- end }}
  {{- end }} # END loadbalancer
  {{- if and .Values.service.challenger.clusterIP (eq .Values.service.challenger.type "ClusterIP") }}
  clusterIP: {{ .Values.service.challenger.clusterIP }}
  {{- end }}
  {{- if .Values.service.challenger.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.challenger.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.challenger.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.challenger.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.service.challenger.ipFamilies }}
  ipFamilies:
  {{- toYaml . | nindent 4 }}
  {{- end -}}
  {{- if .Values.service.challenger.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.challenger.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: wss
    port: {{ .Values.service.challenger.port | default "8082" }}
    targetPort: {{ .Values.service.challenger.targetPort | default "8082" }}
    protocol: TCP
    {{- if .Values.service.challenger.nodePort }}
    nodePort: {{ .Values.service.challenger.nodePort }}
    {{- end }}
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 6 }}