apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
    annotations:
        cert-manager.io/inject-ca-from: entangle-system/entangle-serving-cert
    name: entangle-mutating-webhook-configuration
webhooks:
    - admissionReviewVersions:
        - v1
        - v1alpha1
      clientConfig:
        service:
            name: {{ include "entangle.fullname" . }}-webhook-service
            namespace: {{ .Release.Namespace }}
            path: /mutate-entangle-kairos-io-v1alpha1-entanglement
      failurePolicy: Ignore
      name: mentanglement.kb.io
      rules:
        - apiGroups:
            - ""
          apiVersions:
            - v1
          operations:
            - CREATE
            - UPDATE
          resources:
            - pods
      sideEffects: None
