apiVersion: v1
kind: Service
metadata:
    labels:
        control-plane: controller-manager
    name: {{ include "entangle.fullname" . }}-metrics-service
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - name: https
          port: 8443
          protocol: TCP
          targetPort: https
    selector:
        {{- include "entangle.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ include "entangle.fullname" . }}-webhook-service
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - port: 443
          protocol: TCP
          targetPort: 9443
    selector:
        {{- include "entangle.selectorLabels" . | nindent 6 }}