apiVersion: v1
kind: Service
metadata:
    labels:
        control-plane: controller-manager
    name: '{{ include "helm-chart.fullname" . }}-metrics-service'
    namespace: '{{.Release.Namespace}}'
spec:
    ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: https
    selector:
        {{- include "helm-chart.selectorLabels" . | nindent 6 }}