---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "entangle-proxy.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - {{ include "entangle-proxy.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "entangle-proxy.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
{{- if eq .Values.tls.source "cert-manager-self-signed" }}
    name: {{ include "entangle-proxy.fullname" . }}-selfsigned-issuer
{{- else if eq .Values.tls.source "cert-manager" }}
    name: {{ .Values.tls.certManagerIssuerName }}
{{- end}}
  secretName: {{ include "entangle-proxy.fullname" . }}-webhook-server-cert
---
{{- if eq .Values.tls.source "cert-manager-self-signed" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "entangle-proxy.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}