apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: entangle-proxy-leader-election-role
    namespace: {{ .Release.Namespace }}
rules:
    - apiGroups:
        - ""
      resources:
        - configmaps
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
    - apiGroups:
        - coordination.k8s.io
      resources:
        - leases
      verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
    - apiGroups:
        - ""
      resources:
        - events
      verbs:
        - create
        - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: entangle-proxy-manager-role
rules:
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - create
        - get
        - list
        - update
        - watch
    - apiGroups:
        - batch
      resources:
        - jobs
      verbs:
        - create
        - delete
        - get
        - list
        - update
        - watch
    - apiGroups:
        - entangle-proxy.c3os-x.io
      resources:
        - manifests
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - entangle-proxy.c3os-x.io
      resources:
        - manifests/finalizers
      verbs:
        - update
    - apiGroups:
        - entangle-proxy.c3os-x.io
      resources:
        - manifests/status
      verbs:
        - get
        - patch
        - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: entangle-proxy-metrics-reader
rules:
    - nonResourceURLs:
        - /metrics
      verbs:
        - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: entangle-proxy-proxy-role
rules:
    - apiGroups:
        - authentication.k8s.io
      resources:
        - tokenreviews
      verbs:
        - create
    - apiGroups:
        - authorization.k8s.io
      resources:
        - subjectaccessreviews
      verbs:
        - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: entangle-proxy-leader-election-rolebinding
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: entangle-proxy-leader-election-role
subjects:
    - kind: ServiceAccount
      name: {{ include "entangle-proxy.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: entangle-proxy-manager-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: entangle-proxy-manager-role
subjects:
    - kind: ServiceAccount
      name: {{ include "entangle-proxy.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: entangle-proxy-proxy-rolebinding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: entangle-proxy-proxy-role
subjects:
    - kind: ServiceAccount
      name: {{ include "entangle-proxy.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}