apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "entangle-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "entangle-proxy.labels" . | nindent 4 }}