apiVersion: v1
kind: Service
metadata:
    labels:
        control-plane: controller-manager
    name: {{ include "entangle-proxy.fullname" . }}-metrics-service
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - name: https
          port: 8443
          protocol: TCP
          targetPort: https
    selector:
        {{- include "entangle-proxy.selectorLabels" . | nindent 6 }}